ALTER TABLE actor DROP FOREIGN KEY ACTOR_GAME_MAP_FK;
ALTER TABLE actor DROP INDEX ACTOR_GAME_MAP_FK;
ALTER TABLE actor DROP COLUMN game_map_id;
ALTER TABLE actor DROP COLUMN x;
ALTER TABLE actor DROP COLUMN y;

DROP TABLE map_exit;
DROP TABLE tile;
DROP TABLE tileset;
DROP TABLE start_location;
DROP TABLE game_map;
